### ISSUE TITLE
Wrong size for extra data error

### ISSUE THREAD

**Issue by brogan89** [flathub/com.unity.UnityHub#6]
when trying to install im getting "Error: Failed to install com.unity.UnityHub/x86_64/stable: Wrong size for extra data https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage"

**Comment by Eduardo555** [comment]
hello, the issue are not solved, how can I install? I'm trying and get the same error.

![image](https://user-images.githubusercontent.com/22876123/58927053-94b4e900-8723-11e9-80b4-439d382e7bf4.png)

**Comment by brogan89** [comment]
Yea sorry I should've report that too, but I forgot. I ended up just using the app image straight from [Unity form](https://forum.unity.com/threads/unity-hub-v2-0-0-release.677485/) works every time

**Comment by refi64** [comment]
@Eduardo555 It's been fixed now, apologies for the delay. Unity doesn't have any stable download URLs, so whenever it changes we need to update the checksums and sizes manually in this Flatpak.

**Comment by Eduardo555** [comment]
hey, today i runned the instalation and got success, thanks! @refi64

**Comment by kev005** [comment]
As of June 22, the failure is back for UnityHub 2.0.1 flatpak:

$ flatpak install flathub com.unity.UnityHub
Installing in system:
com.unity.UnityHub/x86_64/stable                  flathub 1624cc7b5bef
  permissions: ipc, network, pulseaudio, x11, dri, multiarch
  file access: host
  dbus access: org.freedesktop.Flatpak, org.gnome.Software
  tags: proprietary
org.freedesktop.Platform.Compat.i386/x86_64/18.08 flathub fb16d111c6b5
Is this ok [y/n]: y
Installing: com.unity.UnityHub/x86_64/stable from flathub
[####################] Downloading files: 1/1 58.1 MB (3.1 MB/s)         
error: Failed to install com.unity.UnityHub/x86_64/stable: Wrong size for extra data https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage

**Comment by refi64** [comment]
@kev005 Should be fixed again.

**Comment by kev005** [comment]
Issue is back again for 2.1.3 UnityHub.

![Screenshot](https://user-images.githubusercontent.com/52118709/71326363-3a148c00-24bf-11ea-91ca-1277f6747e33.png)

**Comment by OrwillT** [comment]
@refi64 This error happend again. Please fix that.

**Comment by haiderkhalid** [comment]
Error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip

this error is still happening. How can i fix it?

**Comment by refi64** [comment]
File a bug on the gravit repo for that.

**Comment by refi64** [comment]
These errors happen on updates but at this point we have a bot that takes care of it, I'm just gonna lock this to avoid any redundant comments. If this happens again and the bot has *not* opened a PR to update it, or an update is not currently being built / published by Flathub, file a new issue.

Any issues related to apps other than Unity Hub should be filed on their respective repos.
